# Generated by Django 3.1.1 on 2020-10-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeedetails',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('dob', models.DateField()),
                ('location', models.IntegerField()),
                ('salary', models.FloatField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
