# Generated by Django 3.1.1 on 2021-01-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp_app', '0002_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('technology', models.CharField(max_length=30)),
                ('describe', models.CharField(max_length=300)),
                ('duration', models.IntegerField()),
                ('affordable_amount', models.IntegerField()),
                ('status', models.CharField(max_length=15)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_app.user')),
            ],
        ),
    ]
