# Generated by Django 3.1.1 on 2021-01-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_app', '0003_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
