# Generated by Django 3.1.1 on 2021-01-03 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sp_app', '0004_auto_20210103_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('technology', models.CharField(max_length=30)),
                ('describe', models.CharField(max_length=300)),
                ('duration', models.IntegerField()),
                ('affordable_amount', models.IntegerField()),
                ('status', models.CharField(max_length=15)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_app.user')),
            ],
        ),
    ]
