# Generated by Django 3.1.1 on 2021-01-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sp_app', '0006_auto_20210103_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('technology', models.CharField(max_length=30)),
                ('describe', models.CharField(max_length=300)),
                ('duration', models.IntegerField()),
                ('affordable_amount', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('status', models.CharField(default='on-going', max_length=15)),
            ],
        ),
    ]
