# Generated by Django 3.1.1 on 2021-01-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_app', '0007_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='describe',
            field=models.CharField(max_length=1000),
        ),
    ]
