# Generated by Django 3.1.1 on 2020-11-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
