# Generated by Django 3.1.1 on 2020-11-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='TecherRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('designation', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=11)),
            ],
        ),
    ]
