# Generated by Django 3.1.1 on 2020-11-15 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iLearn_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=11)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iLearn_App.parentregistration')),
            ],
        ),
    ]
