# Generated by Django 3.1.1 on 2020-11-15 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iLearn_App', '0002_studentregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cls', models.CharField(max_length=30, unique=True)),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=30)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iLearn_App.techerregistration')),
            ],
        ),
    ]
