# Generated by Django 3.1.1 on 2020-11-15 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iLearn_App', '0003_scheduleclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='iLearn_App.studentregistration')),
                ('date', models.DateField()),
                ('attendence', models.IntegerField(default=0)),
            ],
        ),
    ]
