# Generated by Django 3.1.1 on 2020-11-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iLearn_App', '0004_studentinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleclass',
            old_name='cls',
            new_name='subject',
        ),
    ]
