# Generated by Django 3.1.1 on 2020-11-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iLearn_App', '0005_auto_20201115_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='attendence',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='id',
            field=models.ManyToManyField(to='iLearn_App.StudentRegistration'),
        ),
    ]
