# Generated by Django 3.1.1 on 2020-11-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iLearn_App', '0006_auto_20201115_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
