# Generated by Django 3.1.1 on 2020-11-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iLearn_App', '0012_studentinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
