# Generated by Django 3.1.1 on 2020-11-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iLearn_App', '0013_delete_studentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_id', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
