# Generated by Django 3.1.1 on 2020-10-03 06:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employees_Attendance_Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2020, 10, 3))),
                ('status', models.CharField(default='absent', max_length=8)),
                ('start1', models.TimeField(default='0:0:0.0')),
                ('end1', models.TimeField(default='0:0:0.0')),
                ('start2', models.TimeField(default='0:0:0.0')),
                ('end2', models.TimeField(default='0:0:0.0')),
                ('start3', models.TimeField(default='0:0:0.0')),
                ('end3', models.TimeField(default='0:0:0.0')),
                ('start4', models.TimeField(default='0:0:0.0')),
                ('end4', models.TimeField(default='0:0:0.0')),
                ('start5', models.TimeField(default='0:0:0.0')),
                ('end5', models.TimeField(default='0:0:0.0')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization'),
        ),
        migrations.AddField(
            model_name='departments',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization'),
        ),
    ]
