# Generated by Django 3.1.1 on 2020-10-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees_attendance_collection',
            old_name='end1',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='employees_attendance_collection',
            old_name='end2',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='employees_attendance_collection',
            name='end3',
        ),
        migrations.RemoveField(
            model_name='employees_attendance_collection',
            name='end4',
        ),
        migrations.RemoveField(
            model_name='employees_attendance_collection',
            name='end5',
        ),
        migrations.RemoveField(
            model_name='employees_attendance_collection',
            name='start1',
        ),
        migrations.RemoveField(
            model_name='employees_attendance_collection',
            name='start2',
        ),
        migrations.RemoveField(
            model_name='employees_attendance_collection',
            name='start3',
        ),
        migrations.RemoveField(
            model_name='employees_attendance_collection',
            name='start4',
        ),
        migrations.RemoveField(
            model_name='employees_attendance_collection',
            name='start5',
        ),
    ]
