# Generated by Django 3.1.1 on 2020-10-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201003_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees_attendance_collection',
            name='break_time',
            field=models.TimeField(default='0:0:0.0'),
        ),
    ]
